### ISSUE TITLE
Tasarım hakkında bilgilendirme

### ISSUE THREAD

**Issue by delirehberi** [aertas/istanbul-sozlesmesi-yasatir#1]
Kullanılan çerçevenin tasarımı @kadincinayeti@twitter.com ve @kadinmeclisleri@twitter.com hesaplarına aittir. Kullanılan tasarıma ait bilgilendirmenin web sayfasına ve readme dosyasına görünür şekilde eklenmesi gerekmektedir.
Ayrıca facebook üzerinde çerçeveyi kullanmak isteyenler için aşağıdaki bağlantılar da eklenmelidir:
https://m.facebook.com/profilepicframes/?selected_overlay_id=631195867828193&photo_id=104584536806429&_rdr
https://m.facebook.com/profilepicframes/?selected_overlay_id=2952880528093845&photo_id=104584536806429&_rdr

**Comment by aertas** [comment]
Bu çok güzel olmuş eline sağlık. Uygulayacağım.

**Comment by aertas** [comment]
Tasarımın Kadın Cinayetlerini Durduracağız Platformu'na ait olduğu üzere linkini ekledik bu.
